CI:
  - changed-files:
      - any-glob-to-any-file: .github/**
      - any-glob-to-any-file: Makefile

feature:
  - head-branch: ['feat', 'feature']

bug:
  - head-branch: 'fix'

release:
  - base-branch: 'release/'