run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m

  # Include test files or not.
  # Default: true
  tests: true

  # Define the Go version limit.
  # Mainly related to generics support since go1.21.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.21
  go: '1.21'

linters:
  enable:
    - gofumpt
    - unconvert
    - unparam
    - stylecheck
    - gocyclo
    - errorlint
    - prealloc
    - gocritic
    - gci
    - dogsled
    - gosec
    - errcheck

linters-settings:
  stylecheck:
    checks: ["all", "-ST1003"]
  gocyclo:
    min-complexity: 15
  gocritic:
    disabled-checks: ["assignOp", "ifElseChain", "appendAssign"]
  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/functionx/fx-core)
  errcheck:
    check-type-assertions: false
    check-blank: false
