# 当识别到某些特征之后，将自动为 PR 打上对应的标签

name: "Auto Add Labels"

on:
  - pull_request_target

permissions: write-all

jobs:
  auto_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/pr_labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

      - name: Add bug label
        if: startsWith(github.event.pull_request.title, 'fix') && contains(github.event.pull_request.labels, 'bug') == false
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "bug" --remove-label "feature" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add feature label
        if: startsWith(github.event.pull_request.title, 'feat') && contains(github.event.pull_request.labels, 'feature') == false
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "feature" --remove-label "bug" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add 'no publish' label
        if: startsWith(github.event.pull_request.title, 'chore(self)') && contains(github.event.pull_request.labels, 'no publish') == false
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "no publish" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add invalid label
        if: github.event.pull_request.merged == false && github.event.pull_request.state == 'closed'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "invalid" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}