name: Lint Shell

on:
  push:
    branches:
      - main
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/lint_shell.yml'

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        run: make lint-shell
      - name: Run shfmt
        run: docker run --rm -v $(pwd):/mnt -w /mnt mvdan/shfmt:v3.6.0 -l -d -i 2 .
