name: Nightly Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,3,5"
  pull_request:
    paths:
      - '.github/workflows/nightly-tests.yml'

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run go mod
        run: make go.sum

      - name: Run TestIntegrationTest
        run: go test -mod=readonly -v -run TestIntegrationTest ./tests
        env:
          TEST_INTEGRATION: true

      - name: Run TestCrosschainKeeperTestSuite
        run: go test -mod=readonly -v -run TestCrosschainKeeperTestSuite ./x/crosschain/...
        env:
          TEST_INTEGRATION: true