name: Protobuf

on:
  pull_request:
    paths:
      - "proto/**"

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run proto format and generate
        run: |
          docker run --rm --user root --name fx-core-proto-fmt-0.11.2 -v `pwd`:/workspace --workdir /workspace ghcr.io/cosmos/proto-builder:0.11.2 sh ./contrib/protoc/format.sh
          docker run --rm --user root --name fx-core-proto-gen-0.11.2 -v `pwd`:/workspace --workdir /workspace tendermintdev/sdk-proto-gen:v0.7 sh ./contrib/protoc/gen.sh
      - name: Check diff
        run: git diff --exit-code
