name: Solhint

on:
  push:
    paths:
      - "solidity/contracts/**"
  pull_request:
    paths:
      - "solidity/contracts/**"

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  solhint:
    name: runner solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: false
          cache: "yarn"
          cache-dependency-path: solidity/yarn.lock
      - run: cd solidity && yarn install && yarn lint:sol
