name: TestIntegration

on:
  schedule:
    - cron: "0 0 * * 1,3,5"

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run go mod
        run: make go.sum

      - name: Run TestIntegrationTest
        run: go test -mod=readonly -v -run TestIntegrationTest ./tests
        env:
          TEST_INTEGRATION: true

